# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  serializer:
    serialize_null: true
  param_fetcher_listener:  force
  allowed_methods_listener:  true
  routing_loader: false
  view:
    view_response_listener:  'force'

  format_listener:
    rules:
      - { path: '^/api/*', priorities: ['json'], prefer_extension: false }
      - { path: '^/api', priorities: ['html'], prefer_extension: false }
      - { path: '^/', priorities: ['json'], prefer_extension: false }
  body_listener:
    array_normalizer: fos_rest.normalizer.camel_keys
  body_converter:
    enabled: true